"""email accounts and ai extractions

Revision ID: 7f968376af4b
Revises: d383acf48d9b
Create Date: 2026-08-15 00:41:03.808010
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Migrations reference the project's custom column types (GUID, UTCDateTime),
# which autogenerate renders with their full dotted path.
import app.core.types



revision: str = '7f968376af4b'
down_revision: str | None = 'd383acf48d9b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_accounts',
    sa.Column('person_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('imap_host', sa.String(length=255), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('imap_username', sa.String(length=255), nullable=True),
    sa.Column('imap_password_encrypted', sa.Text(), nullable=True),
    sa.Column('imap_use_ssl', sa.Boolean(), nullable=False),
    sa.Column('imap_folders', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_used_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'provider', 'address', name='uq_email_person_provider_address')
    )
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_accounts_person_id'), ['person_id'], unique=False)

    op.create_table('ai_extractions',
    sa.Column('workspace_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('person_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('calendar_event_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_application_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('created_stage_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('linked_existing_application', sa.Boolean(), nullable=False),
    sa.Column('undone_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_stage_id'], ['interview_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_event_id', name='uq_ai_extraction_event')
    )
    with op.batch_alter_table('ai_extractions', schema=None) as batch_op:
        batch_op.create_index('ix_ai_extractions_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_extractions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('email_messages',
    sa.Column('account_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('calendar_event_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('provider_message_id', sa.String(length=512), nullable=False),
    sa.Column('thread_id', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('to_addresses', sa.JSON(), nullable=True),
    sa.Column('sent_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('body_excerpt', sa.Text(), nullable=True),
    sa.Column('match_reasons', sa.JSON(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'provider_message_id', name='uq_email_account_message')
    )
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_messages_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_email_messages_event', ['calendar_event_id'], unique=False)
        batch_op.create_index('ix_email_messages_sent', ['sent_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_email_messages_sent')
        batch_op.drop_index('ix_email_messages_event')
        batch_op.drop_index(batch_op.f('ix_email_messages_account_id'))

    op.drop_table('email_messages')
    with op.batch_alter_table('ai_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_extractions_workspace_id'))
        batch_op.drop_index('ix_ai_extractions_status_created')

    op.drop_table('ai_extractions')
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_accounts_person_id'))

    op.drop_table('email_accounts')
    # ### end Alembic commands ###
