"""jobs

Revision ID: 80445fac75da
Revises: 493607ffc7aa
Create Date: 2026-08-26 22:45:03.466891
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Migrations reference the project's custom column types (GUID, UTCDateTime),
# which autogenerate renders with their full dotted path.
import app.core.types



revision: str = '80445fac75da'
down_revision: str | None = '493607ffc7aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('workspace_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('person_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('application_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('interview_stage_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('offered_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('end_reason', sa.String(length=32), nullable=True),
    sa.Column('end_note', sa.Text(), nullable=True),
    sa.Column('salary_type', sa.String(length=16), nullable=False),
    sa.Column('annual_amount', sa.Float(), nullable=True),
    sa.Column('hourly_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('hours_per_week', sa.Float(), nullable=False),
    sa.Column('weeks_per_year', sa.Float(), nullable=False),
    sa.Column('pay_period', sa.String(length=16), nullable=False),
    sa.Column('first_pay_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interview_stage_id'], ['interview_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_person_start', ['person_id', 'start_date'], unique=False)
        batch_op.create_index('ix_jobs_person_status', ['person_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_person_status')
        batch_op.drop_index('ix_jobs_person_start')

    op.drop_table('jobs')
    # ### end Alembic commands ###
