"""initial schema

Revision ID: d383acf48d9b
Revises: 
Create Date: 2026-08-14 22:19:26.659839
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Migrations reference the project's custom column types (GUID, UTCDateTime),
# which autogenerate renders with their full dotted path.
import app.core.types



revision: str = 'd383acf48d9b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_timezone', sa.String(length=64), nullable=False),
    sa.Column('week_starts_on', sa.Integer(), nullable=False),
    sa.Column('sync_window_past_days', sa.Integer(), nullable=False),
    sa.Column('sync_window_future_days', sa.Integer(), nullable=False),
    sa.Column('auto_detect_interviews', sa.Boolean(), nullable=False),
    sa.Column('followup_after_interview_business_days', sa.Integer(), nullable=False),
    sa.Column('followup_chain_business_days', sa.Integer(), nullable=False),
    sa.Column('waiting_for_feedback_threshold_days', sa.Integer(), nullable=False),
    sa.Column('no_activity_ghosted_threshold_days', sa.Integer(), nullable=False),
    sa.Column('display_timezone_mode', sa.String(length=16), nullable=False),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_types',
    sa.Column('workspace_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('short_label', sa.String(length=32), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('counts_as_technical', sa.Boolean(), nullable=False),
    sa.Column('counts_as_final', sa.Boolean(), nullable=False),
    sa.Column('counts_as_screening', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_interview_type_workspace_key')
    )
    with op.batch_alter_table('interview_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_types_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('people',
    sa.Column('workspace_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_people_workspace_name')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('users',
    sa.Column('workspace_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('last_login_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('calendar_connections',
    sa.Column('person_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_sync_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('last_sync_error_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('sync_window_past_days', sa.Integer(), nullable=True),
    sa.Column('sync_window_future_days', sa.Integer(), nullable=True),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'provider', 'provider_account_id', name='uq_connection_person_provider_account')
    )
    with op.batch_alter_table('calendar_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_connections_person_id'), ['person_id'], unique=False)

    op.create_table('resume_versions',
    sa.Column('person_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_versions_person_id'), ['person_id'], unique=False)

    op.create_table('applications',
    sa.Column('workspace_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('person_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('job_url', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_mode', sa.String(length=16), nullable=False),
    sa.Column('employment_type', sa.String(length=16), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resume_version_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('last_activity_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('archived_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('ix_applications_applied_date', ['applied_date'], unique=False)
        batch_op.create_index('ix_applications_archived_at', ['archived_at'], unique=False)
        batch_op.create_index('ix_applications_company', ['company_name'], unique=False)
        batch_op.create_index('ix_applications_person_status', ['person_id', 'status'], unique=False)
        batch_op.create_index('ix_applications_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('external_calendars',
    sa.Column('connection_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('provider_calendar_id', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('sync_token', sa.Text(), nullable=True),
    sa.Column('last_synced_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['calendar_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'provider_calendar_id', name='uq_calendar_connection_ext_id')
    )
    with op.batch_alter_table('external_calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_calendars_connection_id'), ['connection_id'], unique=False)

    op.create_table('application_notes',
    sa.Column('application_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_notes_application_id'), ['application_id'], unique=False)

    op.create_table('calendar_events',
    sa.Column('person_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('external_calendar_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('connection_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_event_id', sa.String(length=1024), nullable=True),
    sa.Column('ical_uid', sa.String(length=1024), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('organizer_email', sa.String(length=255), nullable=True),
    sa.Column('organizer_name', sa.String(length=255), nullable=True),
    sa.Column('attendees', sa.JSON(), nullable=True),
    sa.Column('starts_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('ends_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('start_timezone', sa.String(length=64), nullable=True),
    sa.Column('end_timezone', sa.String(length=64), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('classification_locked', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('detection_score', sa.Float(), nullable=False),
    sa.Column('detection_reasons', sa.JSON(), nullable=True),
    sa.Column('detection_dismissed', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('deleted_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['calendar_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['external_calendar_id'], ['external_calendars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_calendar_id', 'provider_event_id', name='uq_event_calendar_provider_id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index('ix_calendar_events_classification', ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_external_calendar_id'), ['external_calendar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_ical_uid'), ['ical_uid'], unique=False)
        batch_op.create_index('ix_calendar_events_person_start', ['person_id', 'starts_at'], unique=False)
        batch_op.create_index('ix_calendar_events_starts_at', ['starts_at'], unique=False)

    op.create_table('interview_stages',
    sa.Column('application_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('scheduled_start', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('scheduled_end', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_stages', schema=None) as batch_op:
        batch_op.create_index('ix_stages_application_sequence', ['application_id', 'sequence'], unique=False)
        batch_op.create_index('ix_stages_outcome', ['outcome'], unique=False)
        batch_op.create_index('ix_stages_scheduled_start', ['scheduled_start'], unique=False)
        batch_op.create_index('ix_stages_status', ['status'], unique=False)
        batch_op.create_index('ix_stages_type', ['type_key'], unique=False)

    op.create_table('follow_ups',
    sa.Column('person_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('application_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('interview_stage_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('completed_at', app.core.types.UTCDateTime(), nullable=True),
    sa.Column('snoozed_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('rule_key', sa.String(length=32), nullable=False),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_stage_id'], ['interview_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_ups_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_interview_stage_id'), ['interview_stage_id'], unique=False)
        batch_op.create_index('ix_followups_due_date', ['due_date'], unique=False)
        batch_op.create_index('ix_followups_person_due', ['person_id', 'due_date'], unique=False)
        batch_op.create_index('ix_followups_status_due', ['status', 'due_date'], unique=False)

    op.create_table('interview_events',
    sa.Column('interview_stage_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('calendar_event_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('type_key', sa.String(length=64), nullable=True),
    sa.Column('starts_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('ends_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('interviewer_names', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('sync_state', sa.String(length=32), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interview_stage_id'], ['interview_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_event_id', name='uq_interview_event_calendar_event')
    )
    with op.batch_alter_table('interview_events', schema=None) as batch_op:
        batch_op.create_index('ix_interview_events_stage_start', ['interview_stage_id', 'starts_at'], unique=False)
        batch_op.create_index('ix_interview_events_starts_at', ['starts_at'], unique=False)

    op.create_table('activities',
    sa.Column('workspace_id', app.core.types.GUID(length=36), nullable=False),
    sa.Column('person_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('application_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('interview_stage_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('follow_up_id', app.core.types.GUID(length=36), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', app.core.types.UTCDateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['follow_up_id'], ['follow_ups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interview_stage_id'], ['interview_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activities_application', ['application_id'], unique=False)
        batch_op.create_index('ix_activities_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_activities_person_created', ['person_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_workspace_id'))
        batch_op.drop_index('ix_activities_person_created')
        batch_op.drop_index('ix_activities_created_at')
        batch_op.drop_index('ix_activities_application')

    op.drop_table('activities')
    with op.batch_alter_table('interview_events', schema=None) as batch_op:
        batch_op.drop_index('ix_interview_events_starts_at')
        batch_op.drop_index('ix_interview_events_stage_start')

    op.drop_table('interview_events')
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_index('ix_followups_status_due')
        batch_op.drop_index('ix_followups_person_due')
        batch_op.drop_index('ix_followups_due_date')
        batch_op.drop_index(batch_op.f('ix_follow_ups_interview_stage_id'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_application_id'))

    op.drop_table('follow_ups')
    with op.batch_alter_table('interview_stages', schema=None) as batch_op:
        batch_op.drop_index('ix_stages_type')
        batch_op.drop_index('ix_stages_status')
        batch_op.drop_index('ix_stages_scheduled_start')
        batch_op.drop_index('ix_stages_outcome')
        batch_op.drop_index('ix_stages_application_sequence')

    op.drop_table('interview_stages')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_events_starts_at')
        batch_op.drop_index('ix_calendar_events_person_start')
        batch_op.drop_index(batch_op.f('ix_calendar_events_ical_uid'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_external_calendar_id'))
        batch_op.drop_index('ix_calendar_events_classification')

    op.drop_table('calendar_events')
    with op.batch_alter_table('application_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_notes_application_id'))

    op.drop_table('application_notes')
    with op.batch_alter_table('external_calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_calendars_connection_id'))

    op.drop_table('external_calendars')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_workspace_id'))
        batch_op.drop_index('ix_applications_status')
        batch_op.drop_index('ix_applications_person_status')
        batch_op.drop_index('ix_applications_company')
        batch_op.drop_index('ix_applications_archived_at')
        batch_op.drop_index('ix_applications_applied_date')

    op.drop_table('applications')
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_versions_person_id'))

    op.drop_table('resume_versions')
    with op.batch_alter_table('calendar_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_connections_person_id'))

    op.drop_table('calendar_connections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_workspace_id'))

    op.drop_table('users')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_workspace_id'))

    op.drop_table('people')
    with op.batch_alter_table('interview_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_types_workspace_id'))

    op.drop_table('interview_types')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
